apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: github-runner
        image: dictcp/github-action-runner:latest
        env:
        - name: GITHUB_OWNER
          value: your-organization
        - name: GITHUB_REPOSITORY
          value: your-repository
        - name: RUNNER_TOKEN # stored separately in a Kubernetes secret
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: pat
        - name: DOCKER_TLS_CERTDIR
          value: /certs
        - name: DOCKER_HOST
          value: tcp://localhost:2376
        - name: DOCKER_TLS_VERIFY
          value: "1"
        - name: DOCKER_CERT_PATH
          value: /certs/client
        volumeMounts:
          - name: docker-certs
            mountPath: /certs
      - name: docker
        image: docker:stable-dind
        env:
          - name: DOCKER_TLS_CERTDIR
            value: /certs
        # TODO investigate rootless
        securityContext:
          privileged: true
        volumeMounts:
          - name: docker-storage
            mountPath: /var/lib/docker
          - name: docker-certs
            mountPath: /certs
    volumes:
      - name: docker-storage
        emptyDir: {}
      - name: docker-certs
        emptyDir: {}

